plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-toc
url: "https://daugerdas.github.io/frontendintro.com/"
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - JavaScript.md
  - HTML.md
remote_theme: pages-themes/cayman@v0.2.0
kramdown:
  parse_block_html: true

